# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: lost+found
email: 
description: >-
  I’m Stephen, a developer who loves creating projects that can make a genuine impact on my community. Follow along for projects, thoughts, and deep dives into my latest interests.
github_username: lostplusfound
minimal_mistakes_skin: sunrise
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.27.1
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: 

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Stephen"
  bio: "I’m Stephen, a developer who loves building tech that makes a difference — especially around civic engagement and privacy. Always curious and tinkering, I'm passionate about sharing my journey with others."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://lostplusfound.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lostplusfound"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lostplusfound"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
      
# Collection for portfolio
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
